spring:
    datasource:
        url: jdbc:mysql://localhost:3303/users
        username: admin
        password: password
        driverClassName: com.mysql.cj.jdbc.Driver
        hikari:
            maximum-pool-size: 10
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true